// <auto-generated />
namespace jiujitsutoolbox_apiService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class schoolsandevents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(schoolsandevents));
        
        string IMigrationMetadata.Id
        {
            get { return "201406061451503_schools and events"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
